flappybirdv0:
  env_id: "FlappyBird-v0"
  epsilon_init: 1
  epsilon_min: 0.05
  epsilon_decay: 0.995
  replay_memory_size: 10000
  minibatch_size: 64
  gamma: 0.99
  network_sync_rate: 1000
  learning_rate: 0.001
  alpha: 0.001
  reward_threshold: 1000